config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'static_pages/home'

  get "store/index"

  resources :carts, :line_items

  resources :orders, only: [:new, :create]

  root :to => 'store#index', :as => 'store'

  get '/products_search', to: 'products#search_for_products', as: 'products_search'

  post '/admin/products/:product_id/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/products/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'

  resources :products, only: [:index, :show]

  resources :product_sub_categories, only: [:show]

  resources :product_categories, only: [:show]

  resources :product_categories do
    resources :product_sub_categories do
      resources :products, only: [:index, :show]
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  #PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  MONTHS = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']

  attr_accessor :card_number, :expiry_month, :expiry_year, :cvv
  
  has_many :line_items, dependent: :destroy
  has_many :products, :through => :line_items
  has_paper_trail

  validates :name, :address, :email, :card_number, :expiry_month, :expiry_year, :cvv, presence: true
  validates :cvv, numericality: { only_integer: true }
  validates :expiry_month, inclusion: MONTHS
  #validates :pay_type, inclusion: PAYMENT_TYPES

  monetize :total_price_cents, :as => "total_price"

  accepts_nested_attributes_for :line_items, :allow_destroy => true

  aasm column: 'state' do
    state :pending, initial: true
    state :processing
    state :finished
    state :errored
    
    event :process, after: :charge_card do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end 
  end

  
  def add_line_items_from_cart(cart)
    self.total_price_cents = cart.total_price_cents
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def customer_name
    name
  end

  def customer_email
    email
  end

  def formatted_total_price
    self.total_price.format(:no_cents_if_whole => false, :symbol => true)
  end

  def order_amount
    formatted_total_price
  end

  def total_quantities
    line_items.to_a.sum { |item| item.quantity }
  end

  private

    def permitted_params
      params.require(:order).permit(:name, :address, :email, :pay_type, :card_number, 
        :expiry_month, :expiry_year, :cvv)
    end

    def charge_card
      #begin
        save!
        #charge = Stripe::Charge.create(
        #  amount: self.amount,
        #  currency: "usd",
        #  card: self.stripe_token,
        #  description: self.email
        #)
        #balance = Stripe::BalanceTransaction.retrieve(charge.balance_transaction)
        #self.update(
        #  stripe_id: charge.id,
        #  card_expiration: Date.new(charge.card.exp_year, charge.card.exp_month, 1),
        #  fee_amount: balance.fee
        #)
        self.finish!
      #rescue Stripe::StripeError => e
      #  self.update_attributes(error: e.message)
      #  self.fail!
      #end
    end
end
#ssl_requirement
#active_merchant
#acts_as_list
#acts_as_tree
#annotate_models
#asset_packager
#attachment_fu
#authlogic
#auto_complete
#calendar_date_select
#clearance
#delayed_job

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #skip_before_action :authorize, only: [:new, :create]
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate(:page => params[:page]).order('created_at desc')
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end

    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    @order.process!

    respond_to do |format|
      if @order.finished?
        nullify_cart
        send_notifiers
        format.html { redirect_to store_url, notice: I18n.t('.thanks') }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { 
          flash.now[:alert] = @order.error
          render action: 'new' 
        }
        format.json { render json: @order.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def nullify_cart
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
    end

    def send_notifiers
      OrderNotifier.received(@order).deliver
      OrderNotifier.sale_made(@order).deliver
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type, :card_number, 
        :expiry_month, :expiry_year, :cvv)
    end
  #...
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
.container
  = form_for(@order, html: { class: "form-horizontal", role: "form" }) do |f|
    %br
    %fieldset
      %legend
        Payment Details
      %br
      - if @order.errors.empty?
        .form-group
          = f.label :name, t('.name'), class: "col-sm-3 control-label"
          .col-sm-9
            %input{ :type => "text", :id => "order_name", :name => "order[name]", :class => "form-control", :placeholder => "Card Holder's Name" }
      - else
        %div{ :class => (@order.errors[:name].present?) ? "form-group has-error has-feedback" : "form-group has-success has-feedback" }
          = f.label :name, t('.name'), class: "col-sm-3 control-label"
          .col-sm-7
            %input{ :id => "order_name", :name => "order[name]", :class => "form-control", "aria-invalid" => (@order.errors[:name].present?) ? "true" : "false", "aria-describedby" => "order_nameStatus", :value => @order.name }
            %span{ :class => (@order.errors[:name].present?) ? "glyphicon glyphicon-remove form-control-feedback" : "glyphicon glyphicon-ok form-control-feedback", "aria-hidden" => "true" }
            %span{ :class => "sr-only", :id => "order_nameStatus" }
              = (@order.errors[:name].present?) ? "(error)" : "(success)"
      - if @order.errors.empty?
        .form-group
          = f.label :address, t('.address_html'), class: "col-sm-3 control-label"
          .col-sm-9
            %input{ :type => "text", :id => "order_address", :name => "order[address]", :class => "form-control" }
      - else
        %div{ :class => (@order.errors[:address].present?) ? "form-group has-error has-feedback" : "form-group has-success has-feedback" }
          = f.label :address, t('.address_html'), class: "col-sm-3 control-label"
          .col-sm-7
            %input{ :id => "order_address", :name => "order[address]", :class => "form-control", "aria-invalid" => (@order.errors[:address].present?) ? "true" : "false", "aria-describedby" => "order_addressStatus", :value => @order.address }
            %span{ :class => (@order.errors[:address].present?) ? "glyphicon glyphicon-remove form-control-feedback" : "glyphicon glyphicon-ok form-control-feedback", "aria-hidden" => "true" }
            %span{ :class => "sr-only", :id => "order_addressStatus" }
              = (@order.errors[:address].present?) ? "(error)" : "(success)"
              /@order.errors[:address].join(", ")
      - if @order.errors.empty?
        .form-group
          = f.label :email, t('.email'), class: "col-sm-3 control-label"
          .col-sm-9
            %input{ :type => "email", :id => "order_email", :name => "order[email]", :class => "form-control", :place_holder => "Enter email" }
      - else
        %div{ :class => (@order.errors[:email].present?) ? "form-group has-error has-feedback" : "form-group has-success has-feedback" }
          = f.label :email, t('.email'), class: "col-sm-3 control-label"
          .col-sm-7
            %input{ :id => "order_email", :name => "order[email]", :class => "form-control", "aria-invalid" => (@order.errors[:email].present?) ? "true" : "false", "aria-describedby" => "order_emailStatus", :value => @order.email }
            %span{ :class => (@order.errors[:email].present?) ? "glyphicon glyphicon-remove form-control-feedback" : "glyphicon glyphicon-ok form-control-feedback", "aria-hidden" => "true" }
            %span{ :class => "sr-only", :id => "order_emailStatus" }
              = (@order.errors[:email].present?) ? "(error)" : "(success)"
      - if @order.errors.empty?
        .form-group
          = f.label :card_number, 'Card Number', class: "col-sm-3 control-label"
          .col-sm-9
            %input{ :type => "text", :id => "order_card_number", :name => "order[card_number]", :class => "form-control", :place_holder => "Debit/Credit Card Number" }
      - else
        %div{ :class => (@order.errors[:card_number].present?) ? "form-group has-error has-feedback" : "form-group has-success has-feedback" }
          = f.label :card_number, 'Card Number', class: "col-sm-3 control-label"
          .col-sm-7
            %input{ :id => "order_card_number", :name => "order[card_number]", :class => "form-control", "aria-invalid" => (@order.errors[:card_number].present?) ? "true" : "false", "aria-describedby" => "order_card_numberStatus", :value => @order.card_number }
            %span{ :class => (@order.errors[:card_number].present?) ? "glyphicon glyphicon-remove form-control-feedback" : "glyphicon glyphicon-ok form-control-feedback", "aria-hidden" => "true" }
            %span{ :class => "sr-only", :id => "order_emailStatus" }
              = (@order.errors[:card_number].present?) ? "(error)" : "(success)"
      .form-group
        %label{ :class => "col-sm-3 control-label", :for => "expiry-month" }
          Expiration Date
        .col-sm-9
          .row
            .col-xs-3
              %select{ :class => "form-control col-sm-2", :name => "expiry-month", :id => "expiry-month" }
                %option
                  Month
                %option{ :value => "01" }
                  Jan (01)
                %option{ :value => "02" }
                  Feb (02)
                %option{ :value => "03" }
                  Mar (03)
                %option{ :value => "04" }
                  Apr (04)
                %option{ :value => "05" }
                  May (05)
                %option{ :value => "06" }
                  June (06)
                %option{ :value => "07" }
                  July (07)
                %option{ :value => "08" }
                  Aug (08)
                %option{ :value => "09" }
                  Sep (09)
                %option{ :value => "10" }
                  Oct (10)
                %option{ :value => "11" }
                  Nov (11)
                %option{ :value => "12" }
                  Dec (12)
            .col-xs-3
              %select{ :class => "form-control", :name => "expiry-year" }
                - value = 2015
                - 30.times do
                  %option{ :value => "#{value - 2000}" }
                    = value
                    - value += 1
      - if @order.errors.empty?
        .form-group
          = f.label :cvv, 'Card CVV', class: "col-sm-3 control-label"
          .col-sm-3
            %input{ :type => "text", :id => "order_cvv", :name => "order[cvv]", :class => "form-control", :place_holder => "Security Code" }
      - else
        %div{ :class => (@order.errors[:cvv].present?) ? "form-group has-error has-feedback" : "form-group has-success has-feedback" }
          = f.label :cvv, 'Card CVV', class: "col-sm-3 control-label"
          .col-sm-3
            %input{ :id => "order_cvv", :name => "order[cvv]", :class => "form-control", "aria-invalid" => (@order.errors[:cvv].present?) ? "true" : "false", "aria-describedby" => "order_cvvStatus", :value => @order.cvv }
            %span{ :class => (@order.errors[:cvv].present?) ? "glyphicon glyphicon-remove form-control-feedback" : "glyphicon glyphicon-ok form-control-feedback", "aria-hidden" => "true" }
            %span{ :class => "sr-only", :id => "order_cvvStatus" }
              = (@order.errors[:cvv].present?) ? "(error)" : "(success)"
      .form-group
        .col-sm-offset-3.col-sm-9
          %button{ :type => "submit", :class => "btn btn-success" }
            = t('.submit')

app/views/orders/edit.html.haml
%h1 Editing order
= render 'form'
= link_to 'Show', @order
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders
%table
  %thead
    %tr
      %th Name
      %th Address
      %th Email
      %th> Pay type
      %th
      %th
      %th
  %tbody
    - @orders.each do |order|
      %tr
        %td = order.name
        %td = order.address
        %td = order.email
        %td = order.pay_type
        %td 
          = link_to 'Show', order
        %td 
          = link_to 'Edit', edit_order_path(order)
        %td 
          = link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New Order', new_order_path
%p 
  = paginate @orders

app/views/orders/new.html.haml
/%br
/%hr
/%br
/.order_form
/  %fieldset
/    %legend.legend-title
/      = t('.legend')
/    = render 'form'
= render 'form'

app/views/orders/show.html.haml
.notice
	= notice
%p
	%strong Name
	= @order.name
%p
	%strong Address:
	= @order.address
%p
	%strong Email:
	= @order.email
%p
	%strong Pay type:
	= @order.pay_type
= link_to 'Edit', edit_order_path(@order)
= link_to 'Back', orders_path