config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'static_pages/home'

  get "store/index"

  resources :carts, :line_items

  resources :orders, only: [:new, :create]

  root :to => 'store#index', :as => 'store'

  get '/products_search', to: 'products#search_for_products', as: 'products_search'

  post '/admin/products/:product_id/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/products/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'

  resources :products, only: [:index, :show]

  resources :product_sub_categories, only: [:show]

  resources :product_categories, only: [:show]

  resources :product_categories do
    resources :product_sub_categories do
      resources :products, only: [:index, :show]
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
			current_item.price_cents = current_item.product.price_cents
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

	def total_price_cents
		line_items.to_a.sum { |item| item.total_price_cents }
	end

	def formatted_total_price
        Money.new(total_price).format(:no_cents_if_whole => false, :symbol => true)
    end

    def formatted_est_shipping
        Money.new(0).format(:no_cents_if_whole => false, :symbol => true)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.paginate(:page => params[:page]).order('created_at desc')
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.js { 
          if should_redirect_to_store
            head 302, x_ajax_redirect_url: store_path
          else
            render :destroy
          end
      }
      format.json { head :no_content }
    end
  end

  # ...
  private
  # ...

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def should_redirect_to_store
      request.referrer.include? new_order_url
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
/ %h2 t('.title')
- unless cart.line_items.empty?
	.container
		/.icon-cart3
		.row
			.col-lg-8.col-md-10
				%table.table.table-hover
					%thead
						%tr
							%th
								Product
							%th
								Description
							%th.text-center
								Price
							%th
								Qty
							%th.text-center
								Total
							%th
					%tbody
						= render(cart.line_items)
						%tr
							%td
							%td
							%td
							%td
							%td
								%strong
									Subtotal
							%td.text-right
								%strong
									%strong
										= cart.formatted_total_price
						%tr
							%td
							%td
							%td
							%td
							%td
								%strong
									Est/Shipping
							%td.text-right
								%strong
									= cart.formatted_est_shipping
						%tr
							%td
							%td
							%td
							%td
							%td
								%strong
									Total
							%td.text-right
								%strong
									= cart.formatted_total_price
						%tr
							%td
							%td
							%td
							%td
							%td
								- if (request.original_url == new_order_url) or (request.original_url == orders_url) or (request.referrer == new_order_url and request.xhr?)
									= link_to(content_tag(:span, (' ' + t('.continue_shopping')), class: 'glyphicon glyphicon-shopping-cart'), { :controller => "store", :action => "index" }, { :class => "btn btn-info", :id => "make-white" })
								- else
									= link_to(content_tag(:span, (' ' + t('.checkout')), class: 'glyphicon glyphicon-play'), { :controller => "orders", :action => "new" }, { :method => :get, :class => "btn btn-info", :id => "make-white" })
							%td
								= link_to(content_tag(:span, (' ' + t('.empty')), class: 'glyphicon glyphicon-trash'), { :controller => "carts", :action => "destroy", :id => cart.id, :remote => true }, { :method => :delete, :class => "btn btn-danger", :id => "make-white" })

app/views/carts/_form.html.haml
= form_for(@cart) do |f|
  - if @cart.errors.any?
    .error_explanation
      %h2
        = pluralize(@cart.errors.count, "error") prohibited this cart from being saved:
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li 
            = msg
  .actions
    = f.submit

app/views/carts/destroy.js.erb
$('#notice').hide();
//$('#cart').slideUp(350);
$('#cart').html("");

app/views/carts/edit.html.haml
%h1 Editing cart
= render 'form'
= link_to 'Show', @cart
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts
= will_paginate
%table
  %thead
    %tr
      %th
      %th
      %th
  %tbody
    - @carts.each do |cart|
      %tr
        %td
          = link_to 'Show', cart
        %td
          = link_to 'Edit', edit_cart_path(cart)
        %td
          = link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Cart', new_cart_path
= will_paginate

app/views/carts/new.html.haml
%h1 New cart
= render 'form'
= link_to 'Back', carts_path

app/views/carts/show.html.haml
- if notice
	%p#notice 
		= notice
= render @cart