config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'static_pages/home'

  get "store/index"

  resources :carts, :line_items

  resources :orders, only: [:new, :create]

  root :to => 'store#index', :as => 'store'

  get '/products_search', to: 'products#search_for_products', as: 'products_search'

  post '/admin/products/:product_id/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/products/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'

  resources :products, only: [:index, :show]

  resources :product_sub_categories, only: [:show]

  resources :product_categories, only: [:show]

  resources :product_categories do
    resources :product_sub_categories do
      resources :products, only: [:index, :show]
    end
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	#default_scope { order("id") }
	belongs_to :product
    belongs_to :cart
    belongs_to :order

    monetize :price_cents, :as => "price", :numericality => {
        :greater_than => 0
    }

    validates :product_id, :price_cents, :presence => true
    #validates :product_id, presence: true, uniqueness: { scope: :cart_id, message: "already exist in this cart" }
    validates :quantity, numericality: { greater_than: 0 }

    def product_name
        product.name
    end

    def product_image
        product.image
    end

    def total_price
    	price * quantity
    end

    def total_price_cents
        price_cents * quantity
    end

    def formatted_total_price
        total_price.format(:no_cents_if_whole => false, :symbol => true)
    end

    def formatted_unit_price
        price.format(:no_cents_if_whole => false, :symbol => true)
    end

    private 

      def permitted_params
        params.require(:product).permit(:product_id, :cart_id, :order_id, :price_cents, :quantity)
      end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	#skip_before_action :authorize, only: :create
  #respond_to :html, :js
 	include CurrentCart
 	before_action :set_cart, only: [:create, :destroy]
 	before_action :set_line_item, only: [:show, :edit, :update, :destroy]

 	# GET /line_items
 	# GET /line_items.json
 	def index
 		@line_items = LineItem.paginate(:page => params[:page]).order('id')
 	end

 	# GET /line_items/1
 	# GET /line_items/1.json
 	def show
 	end

  	# GET /line_items/new
  	def new
    	@line_item = LineItem.new
  	end

	# GET /line_items/1/edit
  	def edit
  	end

  	# POST /line_items
  	# POST /line_items.json
  	def create
		  @line_item = @cart.add_product(params[:product_id])
		  respond_to do |format|
        if @line_item.save
          format.html { redirect_to store_url }
        	format.js   { @current_item = @line_item }
        	format.json { render action: 'show', status: :created, location: @line_item }
			  else
				  format.html { render :action => "new" } 
				  format.json { render json: @line_item.errors, status: :unprocessable_entity }
			  end
		  end
	  end

	# PATCH/PUT /line_items/1
  	# PATCH/PUT /line_items/1.json
  	def update
  		respond_to do |format|
  			if @line_item.update(line_item_params)
  				format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
  				format.json { head :no_content }
  			else
  				format.html { render action: 'edit' }
  				format.json { render json: @line_item.errors, status: :unprocessable_entity }
  			end
  		end
  	end

  	# DELETE /line_items/1
  	# DELETE /line_items/1.json
  	def destroy
      update_line_item
      update_cart
      respond_to do |format|
        format.html do 
          redirect_to (:back)
        end
        format.js  do
          if should_go_back_to_store
            head 302, x_ajax_redirect_url: store_path
          else
            render :destroy
          end
        end
        format.json { head :no_content }
      end
  	end

  	private
    	# Use callbacks to share common setup or constraints between actions.
    	def set_line_item
      		@line_item = LineItem.find(params[:id])
    	end

      def update_line_item
        @line_item.quantity -= 1
        if @line_item.quantity == 0
          @line_item.destroy
        else
          @line_item.save
        end
      end

      def update_cart
        if @cart.line_items.empty?
          @cart.destroy
          session[:cart_id] = nil
        end
      end

      def should_go_back_to_store
        (session[:cart_id] == nil) and (request.referrer.include? new_order_url)
      end

      # Never trust parameters from the scary internet, only allow the white
    	# list through.
    	def line_item_params
      		params.require(:line_item).permit(:product_id)
    	end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for(@line_item) do |f|
  - if @line_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@line_item.errors.count, "error") prohibited this line_item from being saved:
      %ul
      - @line_item.errors.full_messages.each do |msg|
        %li
          = msg
  .field
    = f.label :product
    %br
    = f.text_field :product
  .field
    = f.label :cart
    %br
    = f.text_field :cart
  .actions
    = f.submit

app/views/line_items/_invoice_line_items.html.haml
%tr
	%td{ :style => "padding: 0.625em; :colspan => '5'"}
		= line_item.product.name
	%td{ :style => "padding: 0.625em; :colspan => '2'"}
		= line_item.quantity
	%td{ :style => "padding: 0.625em; :colspan => '3'"}
		= line_item.formatted_unit_price
	%td{ :style => "padding: 0.625em; :colspan => '3'"}
		= line_item.formatted_total_price

app/views/line_items/_line_item.html.haml
- if line_item == @current_item
	%tr#current_item
- else
	%tr
%td.col-sm-2.col-md-2
	.media
		%a{ :class => "thumbnail pull-left", :href => "#" }
			= image_tag line_item.product_image, alt: "image for #{line_item.product_name}", class: "media-object", style: "width: 4em; height: 4em;"
%td.col-xs-6.col-sm-6.col-md-6
	.media-body
		= link_to line_item.product_name, product_path(line_item.product)
	%span
		by
		%a{ :href => "#" }
			Brand name
	%span
		Status: 
	%span.text-success
		%strong
			In Stock
%td.col-sm-1.col-md-1.text-center
	%strong
		= line_item.formatted_unit_price	
%td.col-sm-1.col-md-1.text-center
	= line_item.quantity
%td.col-sm-1.col-md-1.text-center
	%strong
		= line_item.formatted_total_price
%td.col-sm-1.col-md-1.text-center
	= link_to(content_tag(:i, nil, class: 'fa fa-arrow-up'), { :controller => "line_items", :action => "create", :product_id => line_item.product_id, :remote => true }, { :method => :post, :class => "btn btn-info btn-sm", id: "make-white" })
	= link_to(content_tag(:i, nil, class: 'fa fa-arrow-down'), line_item, method: :delete, remote: true, class: "btn btn-danger btn-sm", id: "make-white")

app/views/line_items/_line_item.text.haml
= sprintf("%2d  X  %s  @  %s  =  %s\n", line_item.quantity, line_item.product.name, 
	line_item.formatted_unit_price, line_item.formatted_total_price)

app/views/line_items/create.js.erb
$('#notice').hide();
//if ($('#cart tr').length == 1) { 
//	$('#cart').show('blind', 1000); 
//}
$('#cart').html("<%= escape_javascript render(@cart) %>");

//$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/destroy.js.erb
$('#notice').hide();
//if ($('#cart tr').length == 1) { 
//	$('#cart').slideDown(350);
//}
$('#cart').html("<%= escape_javascript render(@cart) %>");

app/views/line_items/edit.html.haml
%h1 Editing line_item
= render 'form'
= link_to 'Show', @line_item %
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items
= will_paginate
%table
  %thead
    %tr
      %th Product
      %th Cart
      %th
      %th
      %th
  %tbody
    - @line_items.each do |line_item|
      %tr
        %td
          = line_item.product
        %td
          = line_item.cart
        %td
          = link_to 'Show', line_item
        %td
          = link_to 'Edit', edit_line_item_path(line_item)
        %td
          = link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Line item', new_line_item_path
= will_paginate

app/views/line_items/new.html.haml
%h1 New line_item
= render 'form'
= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice
	= notice
%p
	%strong Product:
	= @line_item.product
	%strong>Cart:
	= @line_item.cart
= link_to 'Edit', edit_line_item_path(@line_item)
= link_to 'Back', line_items_path