config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'static_pages/home'

  get "store/index"

  resources :carts, :line_items

  resources :orders, only: [:new, :create]

  root :to => 'store#index', :as => 'store'

  get '/products_search', to: 'products#search_for_products', as: 'products_search'

  post '/admin/products/:product_id/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/products/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'
  post '/admin/change_sub_categories', :to => 'admin/product_categories#change_sub_categories'

  resources :products, only: [:index, :show]

  resources :product_sub_categories, only: [:show]

  resources :product_categories, only: [:show]

  resources :product_categories do
    resources :product_sub_categories do
      resources :products, only: [:index, :show]
    end
  end

end

app/views/layouts/_footer.html.haml
%footer{:class => "footer clearfix", :role => "contentinfo" }
  .copyright
    #{Date.today.year} #{ApplicationHelper::STORE_NAME}
  .contact
    %ul.mail-contact
      %li
        Contact us
      %li.icon-mail
        %a{:href => "#"} Email us
    %ul.social-contact
      %li
        Social
      %li.icon-facebook
        %a{:href => "#"} Facebook
      %li.icon-twitter2
        %a{:href => "#"} Twitter
      %li.icon-googleplus2
        %a{:href => "#"} Google+
      %li{ :class => "fa fa-youtube-square fa-lg" }
        %a{:href => "#"} YouTube
      %li.icon-vimeo2
        %a{:href => "#"} Vimeo
      %li.icon-linkedin
        %a{:href => "#"} LinkedIn

/ icon-play fa fa-camera-retro fa-lg

app/views/layouts/_main_store_sidebar.html.haml
.col-md-4.col-lg-3
	%h3.listings-header
		Deals
	.container
		.row
			.offer.offer-default
				.shape
					.shape-text
						top								
				.offer-content
					%h3.lead
						A default offer
					%p
						And a little description.
						%br 
							and so one
			.offer.offer-success
				.shape
					.shape-text
						top								
				.offer-content
					%h3.lead
						A success offer
					%p
						And a little description.
						%br 
							and so one
			.offer.offer-radius.offer-primary
				.shape
					.shape-text
						top
				.offer-content
					%h3.lead
						A primary-radius
					%p
						And a little description.
						%br
							and so one
			.offer.offer-info
				.shape
					.shape-text
						top
				.offer-content
					%h3.lead
						An new info offer
					%p
						And a little description.
						%br
							and so one
			.offer.offer-warning
				.shape
					.shape-text
						top
				.offer-content
					%h3.lead
						A warning offer
					%p
						And a little description.
						%br
							and so one
			.offer.offer-radius.offer-danger
				.shape
					.shape-text
						top
				.offer-content
					%h3.lead
						A danger-radius
					%p
						And a little description.
						%br
							and so one

app/views/layouts/_navigation.html.haml
%nav{ :class => "navbar navbar-trans navbar-fixed-top navbar-inverse", :role => "navigation" }
  .navbar-header
    %button{ :type => "button", :class => "navbar-toggle collapsed", "data-toggle" => "collapse", 
    "data-target" => "#navbar-collapsible" }
      %span.sr-only
        Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a{ :href => "#{store_path}", :class => "navbar-brand" }
      %span{ :class => "glyphicon glyphicon-home", "aria-hidden" => "true" }
  %div{ :class => "collapse navbar-collapse", :id => "navbar-collapsible" }
    %ul{ :class => "nav navbar-nav navbar-left" }
      %li.dropdown.dropdown-large
        %a{ :class => "dropdown-toggle", "data-toggle" => "dropdown", :role => "button", "aria-expanded" => "false" }
          CATEGORIES
          %b.caret
          /%b{ :class => "icon-key icon-white" }
        = render "layouts/product_categories"
    %ul{ :class => "nav navbar-nav navbar-left" }
      %li.drop_down
        %a{ :class => "dropdown-toggle", "data-toggle" => "dropdown", :role => "button", "aria-expanded" => "false" }
          BRANDS
          %b.caret
        /= render "layouts/product_categories"
    = form_tag products_path, :class => "navbar-form form-vertical navbar-left" do |f|
      %div{ :class => "form-group", :style => "display:inline;" }
        .select2-container
          = hidden_field_tag("global-product-search", '', id: 'global-product-search', class: 'select2 ajax', style: 'width: 30em;', data: { source: products_search_path, placeholder: 'Search for a product' })

app/views/layouts/_product_categories.html.haml
%ul{ :class => "dropdown-menu dropdown-menu-large row", :role => "menu", "aria-labelledby" => "dropdownMenu" }
  - ProductCategory.all.each do |product_category|
    - product_sub_categories = product_category.product_sub_categories
    %li.col-sm-4.col-md-4.col-lg-3
      %ul
        %li.dropdown-header
          %a{ :href => "#{product_category_path(product_category)}" }
            = product_category.name
        - product_sub_categories.each do |product_sub_category|
          %li
            = link_to product_sub_category.name, product_sub_category_path(product_sub_category)
        /%li.divider
      

app/views/layouts/_test_navigation.html.haml
/%nav.navbar.navbar-default.navbar-static
%nav{ :class => "navbar navbar-trans navbar-fixed-top navbar-inverse", :role => "navigation" }
  .navbar-header
    %button{ :class => "navbar-toggle", :type => "button", "data-toggle" => "collapse", "data-target" => ".js-navbar-collapse" }
      %span.sr-only
        Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    /%a{ href => "#{store_path}", :class => "navbar-brand" } Large Dropdown Menu
    %a{ :href => "#{store_path}", :class => "navbar-brand" }
  .collapse.navbar-collapse.js-navbar-collapse
    %ul.nav.navbar-nav
      %li.dropdown.dropdown-large
        %a{ :href => "#", :class => "dropdown-toggle", "data-toggle" => "dropdown" }
          CATEGORIES
          %b.caret
        %ul.dropdown-menu.dropdown-menu-large.row
          %li.col-sm-3
            %ul
              %li.dropdown-header
                Glyphicons
              %li
                %a{ :href => "#" }
                  Available glyphs
              %li.disabled
                %a{ :href => "#" }
                  How to use
              %li
                %a{ :href => "#" }
                  Examples
              %li.divider
              %li.dropdown-header
                Dropdowns
              %li
                %a{ :href => "#" }
                  Example
              %li
                %a{ :href => "#" }
                  Aligninment options
              %li
                %a{ :href => "#" }
                  Headers
              %li
                %a{ :href => "#" }
                  Disabled menu items
          %li.col-sm-3
            %ul
              %li.dropdown-header
                Button groups
              %li
                %a{ :href => "#" }
                  Basic example
              %li
                %a{ :href => "#" }
                  Button toolbar
              %li
                %a{ :href => "#" }
                  Sizing
              %li
                %a{ :href => "#" }
                  Nesting
              %li
                %a{ :href => "#" }
                  Vertical variation
              %li.divider
              %li.dropdown-header
                Button dropdowns
              %li
                %a{ :href => "#" }
                  Single button dropdowns
          %li.col-sm-3
            %ul
              %li.dropdown-header
                Input groups
              %li
                %a{ :href => "#" }
                  Basic example
              %li
                %a{ :href => "#" }
                  Sizing
              %li
                %a{ :href => "#" }
                  Checkboxes and radio addons
              %li.divider
              %li.dropdown-header
                Navs
              %li
                %a{ :href => "#" }
                  Tabs
              %li
                %a{ :href => "#" }
                  Pills
              %li
                %a{ :href => "#" }
                  Justified
          %li.col-sm-3
            %ul
              %li.dropdown-header
                Navbar
              %li
                %a{ :href => "#" }
                  Default navbar
              %li
                %a{ :href => "#" }
                  Buttons
              %li
                %a{ :href => "#" }
                  Text
              %li
                %a{ :href => "#" }
                  Non-nav links
              %li
                %a{ :href => "#" }
                  Component alignment
              %li
                %a{ :href => "#" }
                  Fixed to top
              %li
                %a{ :href => "#" }
                  Fixed to bottom
              %li
                %a{ :href => "#" }
                  Static top
              %li
                %a{ :href => "#" }
                  Inverted navbar

app/views/layouts/application.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
<!--[if gt IE 8]><!-->
%html{:class => 'no-js', :lang => 'en'}<>
  <!--<![endif]-->
  %head
    %meta{:charset => "utf-8"}
    %meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }
    %title 
      = ApplicationHelper::STORE_NAME
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = javascript_include_tag "application", "data-turbolinks-track" => true
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
      = javascript_include_tag "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    /docElement.className=docElement.className.replace(/\bno-js\b/,'') + ' js';
    :javascript
      $(document).ready(function() {
        (function(h){h.className = h.className.replace('no-js', 'js')})(document.documentElement);
        $('.select2').each(function(i, e) {
          var select = $(e)
          options = {}
          if (select.hasClass('ajax')) {
            options.ajax = {
              url: select.data('source'),
              quietMillis: 250,
              dataType: 'json',
              data: function(term, page) { return { q: term, page: page, per: 25 } },
              results: function (data, page) {
                return {
                  results: data.products,
                  more: data.total > (page * 25)
                };
              },
            }
            options.minimumInputLength = 2
            options.dropdownCssClass = "bigdrop"
          }
          select.select2(options)
        }); 
      });
      $(document).ready(function() {   
        equalHeight($(".product_thumbnail"));
      });
      $(document).ready(function() { 
        $('#global-product-search').on("change", function(e) {
          top.location.href = "/products/" + e.added.id;
        });
      });
      $(window).resize(function () {
        equalHeight($(".product_thumbnail"));
      });
      $(document).ready(function() { 
        $('#products-wrap .product_thumbnail').mousemove(function() {
          var position = $(this).position();
          $('#cart-image').stop().animate({
            left   : position.left+'px',
            },250,function() {
            });
          }).mouseout(function(){
        });
        $('#products-wrap .btn').click(function() {
          $('#cart-image').css({'-webkit-transform' : 'rotate(20deg)','-moz-transform' : 'rotate(20deg)' });
          setTimeout('angle()',200); 
        });

        $("#cart-image").click(function () {
          if ($("#cart-wrapper").hasClass("height-transition-hidden"))
            $("#cart-wrapper").slideDownTransition();
          else
            $("#cart-wrapper").slideUpTransition();
        });            
      });
    .container-fluid
      = render :partial => "layouts/navigation"
      .row
      /  .column-group
      /    = link_to image_tag("qpm-logo.jpg", alt: "QPM Brand", class: "img-responsive company-logo"), store_path
      .row
        .column-group
          #bottomBar{ :align => "left", :class => "col-xs-12 col-sm-12 col-is-12 col-md-8 col-lg-9" }
            = image_tag "cart.png", id: "cart-image"
          #cart-wrapper.height-transition.height-transition-hidden
            #cart
              = render @cart
      .row
        .column-group
          = yield
      .row
        .column-group
          %hr
          = render :partial => "layouts/footer"
    /[if IE] 
      = javascript_include_tag "ie7.js"